language: ruby
rvm:
  - 2.1.2
env:
  - ADMIN=true
  - BACKEND=true
gemfile:
  - admin/Gemfile
  - backend/Gemfile
bundler_args: --without development --deployment
cache: bundler
matrix:
  exclude:
    - gemfile: admin/Gemfile
      env: BACKEND=true
    - gemfile: backend/Gemfile
      env: ADMIN=true
before_script: "source .before_travis.sh"
script:
  - "bundle exec rake test"
  - "rubocop"
after_script:
  - "cd .."
  - "./.after_travis.sh"
